FROM fedora:29

RUN dnf install -y java-1.8.0-openjdk git curl

ENV http_port 8080

ENV JENKINS_HOME /var/jenkins_home
ENV JENKINS_VERSION 2.150.3
ENV JENKINS_URL https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war

ADD ${JENKINS_URL} /usr/share/jenkins/jenkins.war

EXPOSE ${http_port}

CMD ["java", "-Duser.home=/var/jenkins_home", "-jar", "/usr/share/jenkins/jenkins.war"]
