FROM fedora:29

RUN dnf install -y java-1.8.0-openjdk git curl

ENV HTTP_PORT 8080

ENV UID 1000
ENV GID 1000
ENV USER jenkins
ENV GROUP jenkins
ENV JENKINS_HOME /var/jenkins_home
ENV JENKINS_VERSION 2.150.3
ENV JENKINS_URL https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war

RUN mkdir -p $JENKINS_HOME \
  && chown ${UID}:${GID} $JENKINS_HOME \
  && groupadd -g ${GID} ${GROUP} \
  && useradd -d "$JENKINS_HOME" -u ${UID} -g ${GID} -m -s /bin/bash ${USER}

RUN mkdir -p /usr/share/jenkins/ref/init.groovy.d /var/jenkins_home/init.groovy.d
COPY setupUsers.groovy /var/jenkins_home/init.groovy.d/setupUsers.groovy

ADD ${JENKINS_URL} /usr/share/jenkins/jenkins.war

RUN chown -R ${USER} "$JENKINS_HOME" /usr/share/jenkins

EXPOSE ${HTTP_PORT}

USER ${USER}

COPY start_jenkins.sh /usr/local/bin/start_jenkins.sh

CMD ["/usr/local/bin/start_jenkins.sh"]
